name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.17.0 
  intl: ">=0.15.2 < 0.18.0"
  logging: ^1.1.0
  meta: ^1.8.0
  vector_math: ^2.1.4

dev_dependencies:
  mockito: ^5.3.2 
  test: any
